/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppPresencaRouteImport } from './routes/app.presenca'
import { Route as AppMembrosRouteImport } from './routes/app.membros'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppCozinhaRouteImport } from './routes/app.cozinha'
import { Route as AppCalendarioRouteImport } from './routes/app.calendario'
import { Route as AppAvisosRouteImport } from './routes/app.avisos'
import { Route as AppMembrosIdRouteImport } from './routes/app.membros.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPresencaRoute = AppPresencaRouteImport.update({
  id: '/presenca',
  path: '/presenca',
  getParentRoute: () => AppRoute,
} as any)
const AppMembrosRoute = AppMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppCozinhaRoute = AppCozinhaRouteImport.update({
  id: '/cozinha',
  path: '/cozinha',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppAvisosRoute = AppAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AppRoute,
} as any)
const AppMembrosIdRoute = AppMembrosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMembrosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/avisos': typeof AppAvisosRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/cozinha': typeof AppCozinhaRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/membros': typeof AppMembrosRouteWithChildren
  '/app/presenca': typeof AppPresencaRoute
  '/app/': typeof AppIndexRoute
  '/app/membros/$id': typeof AppMembrosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/avisos': typeof AppAvisosRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/cozinha': typeof AppCozinhaRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/membros': typeof AppMembrosRouteWithChildren
  '/app/presenca': typeof AppPresencaRoute
  '/app': typeof AppIndexRoute
  '/app/membros/$id': typeof AppMembrosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/avisos': typeof AppAvisosRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/cozinha': typeof AppCozinhaRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/membros': typeof AppMembrosRouteWithChildren
  '/app/presenca': typeof AppPresencaRoute
  '/app/': typeof AppIndexRoute
  '/app/membros/$id': typeof AppMembrosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/avisos'
    | '/app/calendario'
    | '/app/cozinha'
    | '/app/financeiro'
    | '/app/membros'
    | '/app/presenca'
    | '/app/'
    | '/app/membros/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/avisos'
    | '/app/calendario'
    | '/app/cozinha'
    | '/app/financeiro'
    | '/app/membros'
    | '/app/presenca'
    | '/app'
    | '/app/membros/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/avisos'
    | '/app/calendario'
    | '/app/cozinha'
    | '/app/financeiro'
    | '/app/membros'
    | '/app/presenca'
    | '/app/'
    | '/app/membros/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/presenca': {
      id: '/app/presenca'
      path: '/presenca'
      fullPath: '/app/presenca'
      preLoaderRoute: typeof AppPresencaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/membros': {
      id: '/app/membros'
      path: '/membros'
      fullPath: '/app/membros'
      preLoaderRoute: typeof AppMembrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cozinha': {
      id: '/app/cozinha'
      path: '/cozinha'
      fullPath: '/app/cozinha'
      preLoaderRoute: typeof AppCozinhaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendario': {
      id: '/app/calendario'
      path: '/calendario'
      fullPath: '/app/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/avisos': {
      id: '/app/avisos'
      path: '/avisos'
      fullPath: '/app/avisos'
      preLoaderRoute: typeof AppAvisosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/membros/$id': {
      id: '/app/membros/$id'
      path: '/$id'
      fullPath: '/app/membros/$id'
      preLoaderRoute: typeof AppMembrosIdRouteImport
      parentRoute: typeof AppMembrosRoute
    }
  }
}

interface AppMembrosRouteChildren {
  AppMembrosIdRoute: typeof AppMembrosIdRoute
}

const AppMembrosRouteChildren: AppMembrosRouteChildren = {
  AppMembrosIdRoute: AppMembrosIdRoute,
}

const AppMembrosRouteWithChildren = AppMembrosRoute._addFileChildren(
  AppMembrosRouteChildren,
)

interface AppRouteChildren {
  AppAvisosRoute: typeof AppAvisosRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppCozinhaRoute: typeof AppCozinhaRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppMembrosRoute: typeof AppMembrosRouteWithChildren
  AppPresencaRoute: typeof AppPresencaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvisosRoute: AppAvisosRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppCozinhaRoute: AppCozinhaRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppMembrosRoute: AppMembrosRouteWithChildren,
  AppPresencaRoute: AppPresencaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
